name: Releases
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      - name: read gradle.properties
        uses: BrycensRanch/read-properties-action@v1
        id: properties
        with:
          file: gradle.properties
          all: true

      - name: publish-fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: A4m2Hcnr
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-tag: ${{ inputs.tag }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: fabric/build/libs/!(*-@(shadow|sources)).jar
          name: ${{ format('[Fabric]LegacyRaid {0} for Minecraft {1}', steps.properties.outputs.mod_version, steps.properties.outputs.minecraft_version) }}
          version: ${{ format('v{0}-mc{1}-fabric', steps.properties.outputs.mod_version, steps.properties.outputs.minecraft_version) }}
          loaders: fabric
          game-versions: ${{ steps.properties.outputs.minecraft_dependency }}

      - name: publish-neoforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: A4m2Hcnr
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: ${{ inputs.tag }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: neoforge/build/libs/!(*-@(shadow|sources)).jar
          name: ${{ format('[NeoForge]LegacyRaid {0} for Minecraft {1}', steps.properties.outputs.mod_version, steps.properties.outputs.minecraft_version) }}
          version: ${{ format('v{0}-mc{1}-neoforge', steps.properties.outputs.mod_version, steps.properties.outputs.minecraft_version) }}
          loaders: neoforge
          game-versions: ${{ steps.properties.outputs.minecraft_dependency }}
